### ISSUE TITLE
Maven Build Failure with update to pom.xml

### ISSUE THREAD

**Issue by vamshikr** [mirswamp/java-api#2]
I am seeing this error when I tried to build the project
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.jar (234 KB at 2953.8 KB/sec)
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.519 s
[INFO] Finished at: 2016-08-24T13:51:26-05:00
[INFO] Final Memory: 21M/149M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project ncsa-swamp: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vamshikr** [comment]
Had to add `-Dgpg.skip` flag to maven build command to avoid the failure.
Example: `mvn clean install -DskipTests -Dmaven.test.skip=true -Dgpg.skip`

**Comment by jjg-123** [comment]
The GPG plugin has been turned off in the pom.

Jeff (Gaynor)
